apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx@sha256:06aa2038b42f1502b59b3a862b1f5980d3478063028d8e968f0810b9b0502380
        ports:
        - containerPort: 8080
